alias au='sudo apt update'
alias auu='sudo apt update && sudo apt upgrade'
alias aps='apt search'
alias ai='sudo apt install'
alias ap='sudo apt purge'
alias ar='sudo apt remove'
alias aar='sudo apt autoremove'

alias sosh='source $ZDOTDIR/.zshrc'
alias esh='vim $ZDOTDIR/.zshrc'
alias mkd='mkdir -pv'
alias bcat='batcat'
